import type { Coordination, VehicleWithDetails } from '@/types/vehicle';
import type { VehicleMaintenance } from '@/hooks/useVehicleMaintenance';
import type { GestorFrota } from '@/hooks/useGestorFrota';

export const MOCK_COORDINATIONS: Coordination[] = [
  { id: 'coord-gpm', name: 'GPM', color: '#0066B3', font_color: '#FFFFFF', order_index: 1 },
  { id: 'coord-cma', name: 'CMA', color: '#10B981', font_color: '#FFFFFF', order_index: 2 },
  { id: 'coord-cmn', name: 'CMN', color: '#F59E0B', font_color: '#000000', order_index: 3 },
  { id: 'coord-cms', name: 'CMS', color: '#8B5CF6', font_color: '#FFFFFF', order_index: 4 },
  { id: 'coord-unmetro', name: 'UN-METRO', color: '#06B6D4', font_color: '#FFFFFF', order_index: 5 },
  { id: 'coord-unsertao', name: 'UN-SERTÃO', color: '#EC4899', font_color: '#FFFFFF', order_index: 6 },
];

export const MOCK_ALL_VEHICLES: VehicleWithDetails[] = [
  {
    plate: 'PCG-4921',
    model: 'Hilux 4x4 Chassi',
    fleet_type: 'Próprio',
    manufacturer: 'Toyota',
    balance: 'R$ 1.850,00',
    fleet_number: 'F-102',
    card_number: '**** 4120',
    current_limit: 'R$ 2.500,00',
    next_period_limit: 'R$ 2.500,00',
    used_value: 'R$ 650,00',
    reserved_value: 'R$ 0,00',
    fuel_type: 'DIESEL',
    description: 'Veículo operacional de manutenção de adutoras',
    vehicle_id: 'v-101',
    image_url: null,
    coordination: MOCK_COORDINATIONS[0],
  },
  {
    plate: 'PDV-8120',
    model: 'Strada Freedom 1.3',
    fleet_type: 'Locado',
    manufacturer: 'Fiat',
    balance: 'R$ 620,00',
    fleet_number: 'F-214',
    card_number: '**** 8821',
    current_limit: 'R$ 1.200,00',
    next_period_limit: 'R$ 1.200,00',
    used_value: 'R$ 580,00',
    reserved_value: 'R$ 0,00',
    fuel_type: 'GASOLINA/ALCOOL',
    description: 'Fiscalização de redes de esgotamento sanitário',
    vehicle_id: 'v-102',
    image_url: null,
    coordination: MOCK_COORDINATIONS[1],
  },
  {
    plate: 'QYN-2A45',
    model: 'Saveiro Robust 1.6',
    fleet_type: 'Próprio',
    manufacturer: 'Volkswagen',
    balance: 'R$ 940,50',
    fleet_number: 'F-305',
    card_number: '**** 5519',
    current_limit: 'R$ 1.500,00',
    next_period_limit: 'R$ 1.500,00',
    used_value: 'R$ 559,50',
    reserved_value: 'R$ 0,00',
    fuel_type: 'FLEX',
    description: 'Atendimento de ocorrências de vazamento',
    vehicle_id: 'v-103',
    image_url: null,
    coordination: MOCK_COORDINATIONS[2],
  },
  {
    plate: 'RGM-3E12',
    model: 'L200 Triton GL',
    fleet_type: 'Locado',
    manufacturer: 'Mitsubishi',
    balance: 'R$ 2.150,00',
    fleet_number: 'F-418',
    card_number: '**** 9034',
    current_limit: 'R$ 3.000,00',
    next_period_limit: 'R$ 3.000,00',
    used_value: 'R$ 850,00',
    reserved_value: 'R$ 0,00',
    fuel_type: 'DIESEL',
    description: 'Supervisão técnica de estações de tratamento (ETA)',
    vehicle_id: 'v-104',
    image_url: null,
    coordination: MOCK_COORDINATIONS[3],
  },
  {
    plate: 'KHD-6718',
    model: 'Toro Freedom Turbo',
    fleet_type: 'Locado',
    manufacturer: 'Fiat',
    balance: 'R$ 180,00',
    fleet_number: 'F-119',
    card_number: '**** 3321',
    current_limit: 'R$ 1.800,00',
    next_period_limit: 'R$ 1.800,00',
    used_value: 'R$ 1.620,00',
    reserved_value: 'R$ 0,00',
    fuel_type: 'DIESEL',
    description: 'Apoio logístico da gerência de máquinas',
    vehicle_id: 'v-105',
    image_url: null,
    coordination: MOCK_COORDINATIONS[0],
  },
  {
    plate: 'PGH-9032',
    model: 'Gol Trendline 1.0',
    fleet_type: 'Próprio',
    manufacturer: 'Volkswagen',
    balance: 'R$ 75,00',
    fleet_number: 'F-522',
    card_number: '**** 1109',
    current_limit: 'R$ 800,00',
    next_period_limit: 'R$ 800,00',
    used_value: 'R$ 725,00',
    reserved_value: 'R$ 0,00',
    fuel_type: 'GASOLINA/ALCOOL',
    description: 'Serviço comercial e leitura de hidrômetros',
    vehicle_id: 'v-106',
    image_url: null,
    coordination: MOCK_COORDINATIONS[4],
  },
  {
    plate: 'NXU-4390',
    model: 'F-4000 4x4 Baú',
    fleet_type: 'Próprio',
    manufacturer: 'Ford',
    balance: 'R$ 0,00',
    fleet_number: 'F-008',
    card_number: '**** 7741',
    current_limit: 'R$ 3.500,00',
    next_period_limit: 'R$ 3.500,00',
    used_value: 'R$ 3.500,00',
    reserved_value: 'R$ 0,00',
    fuel_type: 'DIESEL',
    description: 'Oficina móvel para bombas e motores de poços',
    vehicle_id: 'v-107',
    image_url: null,
    coordination: MOCK_COORDINATIONS[5],
  },
  {
    plate: 'RTE-7B99',
    model: 'Duster Oroch Pro',
    fleet_type: 'Locado',
    manufacturer: 'Renault',
    balance: 'R$ 1.320,00',
    fleet_number: 'F-612',
    card_number: '**** 6620',
    current_limit: 'R$ 1.800,00',
    next_period_limit: 'R$ 1.800,00',
    used_value: 'R$ 480,00',
    reserved_value: 'R$ 0,00',
    fuel_type: 'FLEX',
    description: 'Inspeção de reservatórios e elevatórias',
    vehicle_id: 'v-108',
    image_url: null,
    coordination: MOCK_COORDINATIONS[1],
  },
  {
    plate: 'OYZ-5211',
    model: 'Fiorino Endurance 1.4',
    fleet_type: 'Próprio',
    manufacturer: 'Fiat',
    balance: 'R$ 450,00',
    fleet_number: 'F-720',
    card_number: '**** 2384',
    current_limit: 'R$ 1.000,00',
    next_period_limit: 'R$ 1.000,00',
    used_value: 'R$ 550,00',
    reserved_value: 'R$ 0,00',
    fuel_type: 'FLEX',
    description: 'Transporte de insumos químicos e reagentes',
    vehicle_id: 'v-109',
    image_url: null,
    coordination: null,
  },
  {
    plate: 'RQK-1C88',
    model: 'Ranger XLS 2.2 4x4',
    fleet_type: 'Locado',
    manufacturer: 'Ford',
    balance: 'R$ 890,00',
    fleet_number: 'F-830',
    card_number: '**** 9412',
    current_limit: 'R$ 2.400,00',
    next_period_limit: 'R$ 2.400,00',
    used_value: 'R$ 1.510,00',
    reserved_value: 'R$ 0,00',
    fuel_type: 'DIESEL',
    description: 'Patrulha de mananciais e barragens',
    vehicle_id: 'v-110',
    image_url: null,
    coordination: null,
  },
];

export const MOCK_MAINTENANCE_RECORDS: VehicleMaintenance[] = [
  {
    id: 'm-1',
    plate: 'PCG-4921',
    model: 'Hilux 4x4 Chassi',
    fleet_type: 'Próprio',
    os_number: 84210,
    requested_date: '2026-08-15',
    gad_service_date: '2026-08-18',
    workshop_entry_date: '2026-08-20',
    identified_problems: 'Troca de pastilhas de freio e alinhamento',
    created_at: new Date('2026-08-15').toISOString(),
  },
  {
    id: 'm-2',
    plate: 'NXU-4390',
    model: 'F-4000 4x4 Baú',
    fleet_type: 'Próprio',
    os_number: 84355,
    requested_date: '2026-08-25',
    gad_service_date: '2026-08-26',
    workshop_entry_date: '2026-08-28',
    identified_problems: 'Revisão preventiva de injeção diesel',
    created_at: new Date('2026-08-25').toISOString(),
  },
];

export const MOCK_GESTOR_FROTA: GestorFrota = {
  name: 'Gestor Frota GPM',
  telefone: '(81) 98594-2139',
  email: 'frotagpm@compesa.com.br',
  status_telefone: true,
  status_email: true,
};
